import type { Metadata } from "next";
import { Inter, Geist_Mono, Kantumruy_Pro } from "next/font/google";
import Navbar from "@/src/components/layout/Navbar";
import Footer from "@/src/components/layout/Footer";
import ToastProvider from "@/src/components/providers/ToastProvider";
import { LanguageProvider } from "@/src/context/LanguageContext";
import "./globals.css";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kantumruyPro = Kantumruy_Pro({
  variable: "--font-khmer",
  subsets: ["khmer"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${geistMono.variable} ${kantumruyPro.variable} antialiased`}
      >
        <LanguageProvider>
          <ToastProvider />
          <Navbar />

          {/* All pages render here */}
          <main className="min-h-screen">{children}</main>

          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
